export { default as Favicon } from "/public/images/favicon.png"
export { default as LogoImage } from "/public/images/logo.svg"

export { default as SearchIcon } from "/public/images/search_icon.svg"
export { default as PhoneIcon } from "/public/images/phone_icon.svg"
export { default as TelegramIcon } from "/public/images/telegram_icon.svg"
export { default as PlayIcon } from "/public/images/play_icon.svg"
export { default as CheckCircle } from "/public/images/check_circle.svg"

export { default as PhotoMainBanner } from "/public/images/main_banner_photo.png"
export { default as PhotoIntro_01 } from "/public/images/intro_image_01.png"
export { default as PhotoIntro_02 } from "/public/images/intro_image_02.png"
export { default as PhotoIntro_03 } from "/public/images/intro_image_03.png"
export { default as PhotoBuyCarWeb } from "/public/images/buy_car_web.png"
export { default as PhotoEcoSystem } from "/public/images/ecosystem_community_0021.png"
export { default as PhotoInsightsAmino } from "/public/images/data_insights_amino.png"
export { default as PhotoCarRentalAmino } from "/public/images/car_rental_amico.png"
export { default as PhotoMakingRisk } from "/public/images/making_risk_01.png"
export { default as PhotoInjuryRafiki } from "/public/images/injury_rafiki.png"
export { default as PhotoLeadersInsights } from "/public/images/leaders_in_innovative_insights.png"
export { default as PhotoCharacterInject } from "/public/images/freepik_character_inject.png"
export { default as PhotoDeviceInject } from "/public/images/freepik_device_inject.png"
export { default as PhotoBusinessDealAmino } from "/public/images/business_deal_amico.png"
export { default as PhotoInsuranceAmino } from "/public/images/insurance_amico.png"
export { default as PhotoAuditAmino } from "/public/images/audit_amico.png"
export { default as PhotoParkingAmino } from "/public/images/parking_amico.png"
export { default as PhotoBeneficiosExcel } from "/public/images/beneficios_brickcontrol_excel.png"
export { default as PhotoReportingAutoDescription } from "/public/images/reporting_auto_description.png"
export { default as PhotoReportingAutoId } from "/public/images/reporting_auto_id.png"
export { default as PhotoReportingAutoReport } from "/public/images/reporting_auto_report.png"
export { default as PhotoReportingAutoPlus } from "/public/images/reporting_auto_plus.png"
export { default as PhotoReportingChart } from "/public/images/reporting_chart.png"

export { default as IconCheckSquare } from "/public/images/icon-check-square.svg"
export { default as IconPhone } from "/public/images/icon-phone.svg"
export { default as IconEnvelope } from "/public/images/icon-envelope.svg"

export { default as PhotoUser_01 } from "/public/images/users/01.jpg"
export { default as PhotoUser_02 } from "/public/images/users/02.jpg"
export { default as PhotoUser_03 } from "/public/images/users/03.jpg"
export { default as PhotoUser_04 } from "/public/images/users/04.jpg"
export { default as PhotoUser_05 } from "/public/images/users/05.jpg"
export { default as PhotoUser_06 } from "/public/images/users/06.jpg"
export { default as PhotoUser_07 } from "/public/images/users/07.jpg"
export { default as PhotoUser_08 } from "/public/images/users/08.jpg"
export { default as PhotoUser_09 } from "/public/images/users/09.jpg"
export { default as PhotoUser_10 } from "/public/images/users/10.jpg"

export { default as SocialTwitter } from "/public/images/social-twitter.svg"
export { default as SocialFacebook } from "/public/images/social-facebook.svg"
export { default as SocialLinkedin } from "/public/images/social-linkedin.svg"
export { default as SocialInstagram } from "/public/images/social-instagram.svg"
