export { default as Favicon } from "/public/images/favicon.png"
export { default as LogoImage } from "/public/images/logo.svg"

export { default as PhoneIcon } from "/public/images/phone_icon.svg"
export { default as TelegramIcon } from "/public/images/telegram_icon.svg"
export { default as PlayIcon } from "/public/images/play_icon.svg"

export { default as PhotoMainBanner } from "/public/images/main_banner_photo.png"
export { default as PhotoIntro_01 } from "/public/images/intro_image_01.png"
export { default as PhotoIntro_02 } from "/public/images/intro_image_02.png"
export { default as PhotoIntro_03 } from "/public/images/intro_image_03.png"
export { default as PhotoBuyCarWeb } from "/public/images/buy_car_web.png"
export { default as PhotoEcoSystem } from "/public/images/ecosystem_community_0021.png"

export { default as IconCheckSquare } from "/public/images/icon-check-square.svg"
export { default as IconPhone } from "/public/images/icon-phone.svg"
export { default as IconEnvelope } from "/public/images/icon-envelope.svg"

export { default as PhotoUser_01 } from "/public/images/users/01.jpg"
export { default as PhotoUser_02 } from "/public/images/users/02.jpg"
export { default as PhotoUser_03 } from "/public/images/users/03.jpg"
export { default as PhotoUser_04 } from "/public/images/users/04.jpg"
export { default as PhotoUser_05 } from "/public/images/users/05.jpg"
export { default as PhotoUser_06 } from "/public/images/users/06.jpg"
export { default as PhotoUser_07 } from "/public/images/users/07.jpg"
export { default as PhotoUser_08 } from "/public/images/users/08.jpg"
export { default as PhotoUser_09 } from "/public/images/users/09.jpg"
export { default as PhotoUser_10 } from "/public/images/users/10.jpg"

export { default as SocialTwitter } from "/public/images/social-twitter.svg"
export { default as SocialFacebook } from "/public/images/social-facebook.svg"
export { default as SocialLinkedin } from "/public/images/social-linkedin.svg"
export { default as SocialInstagram } from "/public/images/social-instagram.svg"
